import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const canonical = 'https://if-history.caowenhu.com/'
const escapedCanonical = canonical.replace(/[.*+?^$()|[\]\\]/g, '\\$&')
const index = readFileSync(new URL('../index.html', import.meta.url), 'utf8')
const robots = readFileSync(new URL('../public/robots.txt', import.meta.url), 'utf8')
const sitemap = readFileSync(new URL('../public/sitemap.xml', import.meta.url), 'utf8')
const rights = readFileSync(new URL('../public/rights.txt', import.meta.url), 'utf8')
const thirdPartyNotices = readFileSync(new URL('../public/THIRD-PARTY-NOTICES.txt', import.meta.url), 'utf8')
const business = readFileSync(new URL('../BUSINESS.md', import.meta.url), 'utf8')
const trademarks = readFileSync(new URL('../TRADEMARKS.md', import.meta.url), 'utf8')
const readme = readFileSync(new URL('../README.md', import.meta.url), 'utf8')
const deployWorkflow = readFileSync(new URL('../.github/workflows/deploy.yml', import.meta.url), 'utf8')
const edgeOneDeployDoc = readFileSync(new URL('../docs/DEPLOY-EDGEONE.md', import.meta.url), 'utf8')
const license = readFileSync(new URL('../LICENSE', import.meta.url), 'utf8')
const licenseContent = readFileSync(new URL('../LICENSE-CONTENT.md', import.meta.url), 'utf8')
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))
const packageLock = JSON.parse(readFileSync(new URL('../package-lock.json', import.meta.url), 'utf8'))
const reactLicense = readFileSync(new URL('../node_modules/react/LICENSE', import.meta.url), 'utf8').trim()
const reactDomLicense = readFileSync(new URL('../node_modules/react-dom/LICENSE', import.meta.url), 'utf8').trim()
const schedulerLicense = readFileSync(new URL('../node_modules/scheduler/LICENSE', import.meta.url), 'utf8').trim()
const viteLicense = readFileSync(new URL('../node_modules/vite/LICENSE.md', import.meta.url), 'utf8')
const viteCoreLicense = viteLicense
  .split('# Licenses of bundled dependencies')[0]
  .replace('# Vite core license\nVite is released under the MIT license:\n\n', '')
  .trim()
const cover = readFileSync(new URL('../public/og-cover.png', import.meta.url))

assert.match(index, /<html lang="zh-CN">/)
assert.match(index, /<title>城破前夜：刻下无名｜免费中文历史推演游戏<\/title>/)
assert.match(index, new RegExp('<link rel="canonical" href="' + escapedCanonical + '"'))
assert.match(index, /<meta[\s\S]*?name="description"[\s\S]*?content="《城破前夜：刻下无名》/)
assert.match(index, /<h1>城破前夜：刻下无名<\/h1>/)
assert.match(index, /href="mailto:mckf11111@gmail\.com"/)
assert.match(index, /<link rel="license" href="https:\/\/if-history\.caowenhu\.com\/rights\.txt"/)
assert.doesNotMatch(index, /github\.com\/mckf111\/if-history/, '公开页面不得把私有仓库当作可访问入口')
assert.doesNotMatch(index, /mckf111\.github\.io\/if-history/, '公开页面不得把旧 GitHub Pages 地址作为官方入口')
assert.match(index, /href="https:\/\/beian\.miit\.gov\.cn\/">苏ICP备2024089758号-1<\/a>/)

const jsonLdMatch = index.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/)
assert.ok(jsonLdMatch, '缺少 JSON-LD 结构化数据')
const jsonLd = JSON.parse(jsonLdMatch[1])
assert.deepEqual(jsonLd['@type'], ['VideoGame', 'WebApplication'])
assert.equal(jsonLd.url, canonical)
assert.equal(jsonLd.offers.price, '0')
assert.equal(jsonLd.aggregateRating, undefined, '没有真实评分时不得伪造 aggregateRating')

assert.match(robots, /User-agent: OAI-SearchBot\s+Allow: \//)
assert.match(robots, /User-agent: GPTBot\s+Disallow: \//)
assert.match(robots, new RegExp('Sitemap: ' + escapedCanonical + 'sitemap\\.xml'))
assert.match(sitemap, new RegExp('<loc>' + escapedCanonical + '<\/loc>'))
assert.doesNotMatch(robots + sitemap, /mckf111\.github\.io\/if-history/, '公开索引文件不得保留旧 GitHub Pages 地址')
assert.match(rights, /Copyright © 2026 mckf111（文虎）。保留所有权利。/)
assert.match(rights, /当前版本：v0\.6\.0/)
assert.match(rights, /eebc4849f055562fe0a8e3af17ff95feb8ee2821/)
assert.match(rights, /书面授权与商务合作：mckf11111@gmail\.com/)
assert.match(business, /mailto:mckf11111@gmail\.com/)
assert.match(trademarks, /自 v0\.6\.0 起的专有许可不授予任何项目名称、标志或品牌使用权/)
assert.doesNotMatch(readme, /caowenhu\.gitee\.io\/if-history/, 'README 不得保留已经失效的 Gitee Pages 入口')
assert.match(readme, /docs\/DEPLOY-EDGEONE\.md/)
assert.match(readme, /https:\/\/if-history\.caowenhu\.com\//)
assert.doesNotMatch(readme, /mckf111\.github\.io\/if-history/, 'README 不得把旧 GitHub Pages 地址作为官方入口')
assert.match(deployWorkflow, /edgeone@1\.6\.13 pages deploy \.\/dist/)
assert.match(deployWorkflow, /EDGEONE_API_TOKEN/)
assert.doesNotMatch(deployWorkflow, /GITEE_TOKEN|deploy-gitee|gitee\.com\/api\/v5\/repos/, '发布工作流不得继续调用已下线的 Gitee Pages')
assert.match(edgeOneDeployDoc, /只把构建产物 `dist` 上传给 EdgeOne/)
assert.match(edgeOneDeployDoc, /EDGEONE_API_TOKEN/)
assert.match(license, /PROPRIETARY LICENSE — ALL RIGHTS RESERVED/)
assert.match(license, /生效版本：本项目 v0\.6\.0 及后续版本/)
assert.match(licenseContent, /本次变更不追溯撤销旧版本已经授出的许可/)
assert.equal(packageJson.version, '0.6.0')
assert.equal(packageJson.license, 'UNLICENSED')
assert.equal(packageJson.contentLicense, undefined)
assert.equal(packageLock.version, '0.6.0')
assert.equal(packageLock.packages[''].version, '0.6.0')
assert.equal(packageLock.packages[''].license, 'UNLICENSED')

assert.equal(reactLicense, reactDomLicense, 'React 与 React DOM 的随附许可证应一致')
assert.equal(reactLicense, schedulerLicense, 'React 与 Scheduler 的随附许可证应一致')
assert.match(thirdPartyNotices, /React 19\.2\.7/)
assert.match(thirdPartyNotices, /React DOM 19\.2\.7/)
assert.match(thirdPartyNotices, /Scheduler 0\.27\.0/)
assert.ok(thirdPartyNotices.includes(reactLicense), '公开第三方通知必须包含上游 MIT 许可证原文')
assert.match(thirdPartyNotices, /Vite 8\.1\.4/)
assert.ok(thirdPartyNotices.includes(viteCoreLicense), '公开第三方通知必须包含 Vite core MIT 许可证原文')

assert.equal(cover.subarray(1, 4).toString(), 'PNG')
assert.equal(cover.readUInt32BE(16), 1200)
assert.equal(cover.readUInt32BE(20), 630)

console.log('公开发布面检查通过：元数据、私有仓库边界、EdgeOne 构建产物部署边界、v0.6.0 专有许可、旧版本边界、第三方 MIT 通知、商务入口、商标说明与 1200×630 分享图一致。')
