import type { ClaimDefinition } from '../types'

// 断言表：信念的原子单位。
// truth 指「本局虚构世界内」的真值，供事实层编年史与反证机制使用；
// 与真实历史的对照一律写在 boundary（史实部分给 sourceId，纯架空引用 counterfactual 或不引）。
export const CLAIMS: ClaimDefinition[] = [
  // ── 时局（无撬点，铺垫恐惧与轻信） ──
  {
    id: 'c-city-falls',
    text: '居庸关已失，宣府大同尽降，京师旦夕不保。',
    truth: 'true',
    kind: 'rumor',
    aboutNpcIds: [],
    sourceId: 'mingshi-benji',
    boundary: '三月中旬居庸关不守、京师危殆属史实（《明史·庄烈帝纪》）；市井传言的具体措辞为架空拟写。',
  },
  {
    id: 'c-prince-south',
    text: '太子已奉密旨微服南下。',
    truth: 'unresolvable',
    kind: 'rumor',
    aboutNpcIds: [],
    sourceId: 'jiashen-chuanxin',
    boundary: '甲申之际太子下落史载歧异，本作不取定论；城中此类讹言纷起的氛围有《甲申传信录》可证，具体传言为架空拟写。',
  },
  {
    id: 'c-mercy-order',
    text: '破城之军有令：开门迎者秋毫无犯。',
    truth: 'unresolvable',
    kind: 'rumor',
    aboutNpcIds: [],
    sourceId: 'jiashen-chuanxin',
    boundary: '大顺军入城初期约束军纪的记载见于诸野史而互有出入；本句作城中流言处理，为架空拟写。',
  },

  // ── 撬点「门」：孙把总的信与惧 ──
  {
    id: 'c-pay-coming',
    text: '户部欠饷已有着落，三日内解到各汛。',
    truth: 'false',
    kind: 'order',
    aboutNpcIds: ['sun-bazong'],
    leverId: 'gate',
    sourceId: 'mingshi-benji',
    boundary: '京营久欠粮饷属史实背景；「饷银将至」为架空断言，史无其事——它是守军最想信的一句谎。',
  },
  {
    id: 'c-scapegoat-list',
    text: '兵部已拟失门问罪名单，把总以上皆在列。',
    truth: 'false',
    kind: 'order',
    aboutNpcIds: ['sun-bazong'],
    leverId: 'gate',
    boundary: '架空推演：史上未见此名单；「失门必究」的恐惧符合明末军法氛围，故此谎可信。',
  },
  {
    id: 'c-abandon-outer',
    text: '上头已密议弃守外城，各汛自寻生路。',
    truth: 'unresolvable',
    kind: 'order',
    aboutNpcIds: ['sun-bazong'],
    leverId: 'gate',
    boundary: '十八日外城陷落属史实；「密议弃守」之说史无明证，本局作城中讹言处理，为架空拟写。',
  },
  {
    id: 'c-sun-family-boat',
    text: '渡口有船家肯载军眷出城，只认现银。',
    truth: 'true',
    kind: 'logistics',
    aboutNpcIds: ['sun-bazong', 'wu-qiniang'],
    leverId: 'gate',
    sourceId: 'counterfactual',
    boundary: '架空推演：船家与渡口人事为本作虚构；「军眷出逃需重金」符合围城情理。这句话要两头都信才成一桩买卖。',
  },

  // ── 撬点「册」：钱司吏与匠籍名册 ──
  {
    id: 'c-roster-to-camp',
    text: '匠籍名册将誊送营中，破城后按册征发匠户。',
    truth: 'true',
    kind: 'order',
    aboutNpcIds: ['qian-sili'],
    leverId: 'roster',
    sourceId: 'da-ming-huidian',
    boundary: '明代匠籍与佥派制度属史实背景（《大明会典》）；本局中这份名册及其誊送安排为架空推演。',
  },
  {
    id: 'c-audit-coming',
    text: '有御史衔命清查各司册档，三日内到部。',
    truth: 'false',
    kind: 'order',
    aboutNpcIds: ['qian-sili'],
    leverId: 'roster',
    boundary: '架空断言：城破前夕已无此等清查；但钱司吏对查账的恐惧，会替这句谎作保。',
  },
  {
    id: 'c-new-master-values-roster',
    text: '新主进城先索匠籍，献册者得录用。',
    truth: 'unresolvable',
    kind: 'rumor',
    aboutNpcIds: ['qian-sili'],
    leverId: 'roster',
    sourceId: 'jiashen-chuanxin',
    boundary: '大顺入京后追赃、征用工匠的记载见于野史；「献册录用」为架空拟写的市井推测。',
  },
  {
    id: 'c-he-implicated',
    text: '兵马司在追查经手火票戳记的外匠。',
    truth: 'false',
    kind: 'order',
    aboutNpcIds: ['master-he'],
    boundary: '架空推演：火票戳记外包民间刻铺为本作虚构；「追查外匠」为局中可被伪造的恐吓。',
  },
  {
    id: 'c-buyers-exist',
    text: '有人出五十两白银收匠册抄件。',
    truth: 'unresolvable',
    kind: 'rumor',
    aboutNpcIds: ['zhao-si', 'qian-sili'],
    leverId: 'roster',
    boundary: '架空拟写：乱前文书买卖无实据；乱世贩卖册籍之事符合时代情理。',
  },
  {
    id: 'c-xiaoman-not-listed',
    text: '姚记代工姚小满一户不在匠册。',
    truth: 'false',
    kind: 'identity',
    aboutNpcIds: [],
    leverId: 'roster',
    boundary: '架空推演：姚小满为虚构人物，她在册与否只存在于本局世界——而她确实在册。',
  },
  {
    id: 'c-roster-burn-order',
    text: '司中已奉令：城危之日册档当焚，勿使资敌。',
    truth: 'false',
    kind: 'order',
    aboutNpcIds: ['qian-sili'],
    leverId: 'roster',
    boundary: '架空断言：史上册档多毁于兵乱，然「奉令当焚」为局中可伪造之令，史无此令。',
  },

  // ── 撬点「人」：春生、粮船与水门 ──
  {
    id: 'c-chun-transfer',
    text: '运夫营明日拔营随军转输，不再回城。',
    truth: 'true',
    kind: 'logistics',
    aboutNpcIds: ['chunsheng'],
    leverId: 'chunsheng',
    sourceId: 'counterfactual',
    boundary: '架空推演：姚春生与运夫营为本作虚构；「军前佥派民夫随营转输」符合明末兵事常例。这是弟弟头上的倒计时。',
  },
  {
    id: 'c-chun-sick',
    text: '运夫姚春生染时疫，例当遣出营外。',
    truth: 'false',
    kind: 'identity',
    aboutNpcIds: ['chunsheng'],
    leverId: 'chunsheng',
    boundary: '架空推演：春生并未染疫——这是一张可以伪造的病牒；「疫者出营」的营规符合时代常理。',
  },
  {
    id: 'c-boat-requisition',
    text: '兵马司已行文，吴家粮船列入征用。',
    truth: 'false',
    kind: 'logistics',
    aboutNpcIds: ['wu-qiniang'],
    leverId: 'chunsheng',
    boundary: '架空推演：征用行文并不存在——但它是吴七娘最怕的一句话，恐惧会替它作保。',
  },
  {
    id: 'c-boat-hire',
    text: '吴家船受雇装北货，十九日晨出水门，已报关防。',
    truth: 'false',
    kind: 'logistics',
    aboutNpcIds: ['wu-qiniang'],
    leverId: 'chunsheng',
    boundary: '架空推演：受雇装货为可伪造的过关名目；水门验票放行的规矩为本局虚构设定。',
  },
  {
    id: 'c-roster-copied',
    text: '匠册已有抄页流出坊间。',
    truth: 'unresolvable',
    kind: 'rumor',
    aboutNpcIds: ['qian-sili'],
    leverId: 'roster',
    boundary: '架空拟写：是否真有抄页流出，取决于这一局里的人做了什么——它可以从谎话变成事实。',
  },

  // ── 通行（工具型断言） ──
  {
    id: 'c-huopiao-pass',
    text: '持兵马司火票者，夜禁门禁皆得通行。',
    truth: 'true',
    kind: 'order',
    aboutNpcIds: [],
    sourceId: 'da-ming-huidian',
    boundary: '火票为明代急递勘合类文书、可通关禁属制度背景（《大明会典》驿传）；本局具体式样为架空拟制。',
  },
]

export const CLAIMS_BY_ID: Record<string, ClaimDefinition> = Object.fromEntries(
  CLAIMS.map((claim) => [claim.id, claim]),
)
