import type { NpcDefinition } from '../types'

// 人物表（M1 先行 4 人；M2 扩到 8 人）。
// 设计铁律：欲望与恐惧必须机制承重——desireClaimIds 决定他想信什么（验看时查得松），
// fearClaimIds 决定恐惧型断言对他「宁可信其有」，并作为节点日决策输入。
// 姚小满是玩家实体，不入此表。

export const NPCS: NpcDefinition[] = [
  {
    id: 'master-he',
    name: '何师傅',
    role: '刻字铺掌柜',
    mark: '木',
    brief: '你的东家。手艺硬，胆子小，一家六口都在铺子后头住。',
    desire: '保住铺子，让一家人囫囵个儿熬过这场兵灾。',
    fear: '官面上的活计出纰漏，全家跟着吃挂落。',
    desireClaimIds: ['c-mercy-order'],
    fearClaimIds: ['c-he-implicated'],
    acumen: 2,
    stance: '他不问时局，只问今天的活计交不交得出去。可他夜里睡不着的样子，你在阁楼上听得见。',
    edges: [
      { to: 'zhao-si', kind: 'trade', strength: 1 },
      { to: 'qian-sili', kind: 'duty', strength: 1 },
    ],
    schedule: {
      '16-0': 'keji-shop', '16-1': 'keji-shop', '16-2': 'zhipu', '16-3': 'keji-shop',
      '17-0': 'keji-shop', '17-1': 'keji-shop', '17-2': 'keji-shop', '17-3': 'keji-shop',
      '18-0': 'keji-shop', '18-1': 'keji-shop', '18-2': 'keji-shop', '18-3': 'keji-shop',
    },
    initialBeliefs: { 'c-city-falls': 2 },
    secrets: [
      { id: 'he-scrap-seal', text: '何师傅替兵马司刻过火票戳记，作废的一枚旧版没有上缴，压在柜底。' },
      { id: 'he-debt', text: '铺子欠着南纸店两季的纸钱，何师傅正打算把学徒的工钱也押后。' },
    ],
    canCarry: false,
  },
  {
    id: 'zhao-si',
    name: '赵四',
    role: '递书脚夫',
    mark: '路',
    brief: '给各衙门递书的脚夫，哪条街都熟，哪边的钱都赚。',
    desire: '乱世里攒够能换命的东西——银子，或者把柄。',
    fear: '城破那天两手空空，跟路边的饿殍换不出一个身位。',
    desireClaimIds: ['c-buyers-exist'],
    fearClaimIds: ['c-city-falls'],
    acumen: 3,
    stance: '他说他只是跑腿的。可他捎的每一封书，都先在他心里过了一遍秤。',
    edges: [
      { to: 'master-he', kind: 'trade', strength: 1 },
      { to: 'qian-sili', kind: 'trade', strength: 2 },
      { to: 'sun-bazong', kind: 'trade', strength: 1 },
    ],
    schedule: {
      '16-0': 'yamen', '16-1': 'dukou', '16-2': 'chengmen', '16-3': 'nanpeng',
      '17-0': 'dukou', '17-1': 'yamen', '17-2': 'nanpeng', '17-3': 'chengmen',
      '18-0': 'yamen', '18-1': 'chengmen', '18-2': 'dukou', '18-3': 'nanpeng',
    },
    initialBeliefs: { 'c-city-falls': 2, 'c-buyers-exist': 1 },
    secrets: [
      { id: 'zhao-paizi', text: '赵四挂着兵马司的递书腰牌，宵禁后也能走街。他捎东西从不问来路，只问价钱。' },
      { id: 'zhao-stash', text: '赵四在难民棚后头藏了个包袱，里头是他这些日子替人捎带时「漏下」的零碎。' },
    ],
    canCarry: true,
    carryBias: 'sell',
  },
  {
    id: 'sun-bazong',
    name: '孙把总',
    role: '外城门把总',
    mark: '门',
    brief: '守外城门的低阶武官，手底下三十来个兵，饷银欠了六个月。',
    desire: '给弟兄们讨到欠饷；讨不到，就在乱起来之前给家眷找条后路。',
    fear: '城破之日，「失门」的罪名头一个落在他头上。',
    desireClaimIds: ['c-pay-coming', 'c-mercy-order'],
    fearClaimIds: ['c-scapegoat-list', 'c-city-falls'],
    acumen: 2,
    stance: '他把门锁了又检查一遍，不是尽忠，是怕。怕上头，怕城外，也怕手底下那些饿红了眼的兵。',
    edges: [
      { to: 'qian-sili', kind: 'duty', strength: 1 },
      { to: 'zhao-si', kind: 'trade', strength: 1 },
    ],
    schedule: {
      '16-0': 'chengmen', '16-1': 'chengmen', '16-2': 'dukou', '16-3': 'chengmen',
      '17-0': 'chengmen', '17-1': 'yamen', '17-2': 'chengmen', '17-3': 'chengmen',
      '18-0': 'chengmen', '18-1': 'chengmen', '18-2': 'chengmen', '18-3': 'chengmen',
    },
    initialBeliefs: { 'c-city-falls': 1, 'c-pay-coming': 1 },
    secrets: [
      { id: 'sun-boat-ask', text: '孙把总前夜便衣去过渡口，问的是一船能装几口人、要多少银子。他的家眷还在城里。' },
      { id: 'sun-arrears', text: '汛里的兵六个月没见饷银，孙把总把自己的马卖了，抵了半月口粮。' },
    ],
    canCarry: false,
    probeSuspicion: 1,
  },
  {
    id: 'qian-sili',
    name: '钱司吏',
    role: '兵马司书吏',
    mark: '册',
    brief: '管册档与佥派的老书吏，一手好字，一手好算盘。',
    desire: '把手里的名册变成新朝的进身之阶——或者，一笔够远走的横财。',
    fear: '册库里他历年吃空额的痕迹，被人当着上官的面翻出来。',
    desireClaimIds: ['c-new-master-values-roster'],
    fearClaimIds: ['c-audit-coming'],
    acumen: 3,
    stance: '他见过三任司官来了又走，册库的钥匙始终在他腰上。他说：朝廷会亡，册不会。',
    edges: [
      { to: 'master-he', kind: 'duty', strength: 1 },
      { to: 'zhao-si', kind: 'trade', strength: 2 },
      { to: 'sun-bazong', kind: 'duty', strength: 1 },
    ],
    schedule: {
      '16-0': 'yamen', '16-1': 'yamen', '16-2': 'zhipu', '16-3': 'yamen',
      '17-0': 'yamen', '17-1': 'chengmen', '17-2': 'yamen', '17-3': 'yamen',
      '18-0': 'yamen', '18-1': 'yamen', '18-2': 'yamen', '18-3': 'yamen',
    },
    initialBeliefs: { 'c-city-falls': 2, 'c-new-master-values-roster': 1, 'c-roster-to-camp': 3 },
    secrets: [
      { id: 'qian-sleeve', text: '钱司吏这几日把册库里的某几页单独抽了出来，收进随身的袖箱。' },
      { id: 'qian-graft', text: '历年匠户佥派，钱司吏吃过空额——名册上有几户早已亡故，工食银照领。' },
    ],
    canCarry: false,
    probeSuspicion: 1,
  },
  {
    id: 'douzi',
    name: '豆子',
    role: '刷印学徒',
    mark: '墨',
    brief: '铺里的刷印学徒，手快，嘴也快，总觉得自己该干件大事。',
    desire: '被人看得起——最好是干成一件人人都会念叨的大事。',
    fear: '被何师傅赶出铺子，回到没人要的日子。',
    desireClaimIds: ['c-prince-south'],
    fearClaimIds: ['c-he-implicated'],
    acumen: 1,
    stance: '他给难民棚送浆糊和旧纸，说是何师傅让送的。何师傅没让。',
    edges: [
      { to: 'master-he', kind: 'duty', strength: 2 },
      { to: 'su-popo', kind: 'trade', strength: 1 },
    ],
    schedule: {
      '16-0': 'keji-shop', '16-1': 'keji-shop', '16-2': 'nanpeng', '16-3': 'keji-shop',
      '17-0': 'keji-shop', '17-1': 'keji-shop', '17-2': 'nanpeng', '17-3': 'keji-shop',
      '18-0': 'keji-shop', '18-1': 'nanpeng', '18-2': 'keji-shop', '18-3': 'keji-shop',
    },
    initialBeliefs: { 'c-city-falls': 1, 'c-prince-south': 1 },
    secrets: [
      { id: 'douzi-blocks', text: '豆子偷偷攒下了拆版剩的旧字钉，说够拼半页告示。他管那木匣叫"家底"。' },
      { id: 'douzi-hero', text: '豆子在难民棚听书听多了，认定乱世里"把名字印出来"就能救人——他在等一个由头。' },
    ],
    canCarry: true,
    carryBias: 'alter',
  },
  {
    id: 'wu-qiniang',
    name: '吴七娘',
    role: '运粮船主',
    mark: '舟',
    brief: '东便门渡口的船主，一条粮船，七个船工，说一不二。',
    desire: '把船和船工囫囵个儿带出这场乱子。',
    fear: '船被官面征走，或者被乱兵凿沉在水门里。',
    desireClaimIds: ['c-mercy-order'],
    fearClaimIds: ['c-boat-requisition'],
    acumen: 2,
    stance: '她嘴上把价钱咬得死死的，夜里却叫人往粥棚送米。她不许人说。',
    edges: [
      { to: 'zhao-si', kind: 'trade', strength: 1 },
      { to: 'su-popo', kind: 'debt', strength: 1 },
      { to: 'chunsheng', kind: 'trade', strength: 1 },
    ],
    schedule: {
      '16-0': 'dukou', '16-1': 'dukou', '16-2': 'dukou', '16-3': 'dukou',
      '17-0': 'dukou', '17-1': 'dukou', '17-2': 'nanpeng', '17-3': 'dukou',
      '18-0': 'dukou', '18-1': 'dukou', '18-2': 'dukou', '18-3': 'dukou',
    },
    initialBeliefs: { 'c-city-falls': 2 },
    secrets: [
      { id: 'wu-price', text: '吴七娘私下的价：一口人三两，孩童减半。她嘴上骂人，收了钱就认账。' },
      { id: 'wu-mi', text: '粥棚那口锅里，有两成米是吴七娘夜里叫人悄悄送的。她不许人说。' },
    ],
    canCarry: true,
    carryBias: 'pocket',
  },
  {
    id: 'chunsheng',
    name: '姚春生',
    role: '被征的运夫',
    mark: '结',
    brief: '你弟弟。上月被征进运夫营，如今拘在城门汛地里搬粮包。',
    desire: '活着回家。别的他不敢想。',
    fear: '被当成逃兵吊在营门口——营里上个月吊过一个。',
    desireClaimIds: ['c-chun-sick'],
    fearClaimIds: ['c-chun-transfer'],
    acumen: 1,
    stance: '他手腕上系着东渡口运夫互认的红绳结。他托人带话：别拿粮换他。',
    edges: [
      { to: 'sun-bazong', kind: 'duty', strength: 1 },
      { to: 'wu-qiniang', kind: 'trade', strength: 1 },
    ],
    schedule: {
      '16-0': 'chengmen', '16-1': 'chengmen', '16-2': 'chengmen', '16-3': 'chengmen',
      '17-0': 'chengmen', '17-1': 'chengmen', '17-2': 'chengmen', '17-3': 'chengmen',
      '18-0': 'chengmen', '18-1': 'chengmen', '18-2': 'chengmen', '18-3': 'chengmen',
    },
    initialBeliefs: { 'c-chun-transfer': 1 },
    secrets: [
      { id: 'chun-word', text: '春生托人往家里带过一句话：别拿粮换他——姐姐的活计要养活的不止他一个。' },
      { id: 'chun-cord', text: '春生手腕上的红绳结，是东渡口运夫互认的结法。渡口的人见结如见人。' },
    ],
    canCarry: false,
  },
  {
    id: 'su-popo',
    name: '苏婆婆',
    role: '难民棚的主心骨',
    mark: '灯',
    brief: '难民棚里说话最管用的老妇人。不识字，记性比册子还牢。',
    desire: '把棚里的孩子一个个喂活，能送出城的都送出去。',
    fear: '兵乱烧到棚里——棚是草搭的。',
    desireClaimIds: ['c-mercy-order'],
    fearClaimIds: ['c-city-falls'],
    acumen: 0,
    stance: '她不识字，可谁的话能信、谁的眼神发虚，她一打眼就知道。只是文书骗不骗她，她真看不出来。',
    edges: [
      { to: 'douzi', kind: 'trade', strength: 1 },
      { to: 'wu-qiniang', kind: 'debt', strength: 1 },
    ],
    schedule: {
      '16-0': 'nanpeng', '16-1': 'nanpeng', '16-2': 'nanpeng', '16-3': 'nanpeng',
      '17-0': 'nanpeng', '17-1': 'nanpeng', '17-2': 'nanpeng', '17-3': 'nanpeng',
      '18-0': 'nanpeng', '18-1': 'nanpeng', '18-2': 'nanpeng', '18-3': 'nanpeng',
    },
    initialBeliefs: { 'c-city-falls': 2 },
    secrets: [
      { id: 'su-count', text: '苏婆婆记得棚里每个孩子是从哪个门进来的。她不识字，全凭心记。' },
      { id: 'su-silver', text: '苏婆婆攒着一小包碎银——不够一口人的船钱。那是给棚里最小那个孩子留的。' },
    ],
    canCarry: false,
  },
]

export const NPCS_BY_ID: Record<string, NpcDefinition> = Object.fromEntries(
  NPCS.map((npc) => [npc.id, npc]),
)
